### ISSUE TITLE
Can't connect and get errors

### ISSUE THREAD

**Issue by KrunchMuffin** [AntonShuvaev/elasticsearch4idea#102]
I created an API key and I can't connect either Kibana or Elastic.

{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}

I noticed realm=security but when I create an api key it seems to assign a realm, mine is `cloud-saml-kibana`

**Comment by AntonShuvaev** [comment]
I think the problem is that SAML realm is not suitable for using Elasticsearch by REST API. You need to configure other realm or try to login using Kibana.

**Comment by AntonShuvaev** [comment]
I've released an update that fixes connecting to Kibana. Can you try again and let me know if it works for you?

**Comment by KrunchMuffin** [comment]
I didn't try the api, but i got connected with the web login
