### ISSUE TITLE
Change the Font Size of the Table and JSON Views

### ISSUE THREAD

**Issue by afluegge** [AntonShuvaev/elasticsearch4idea#104]
### Is your feature request related to a problem?

Difficult to read the Text in Table or JSON Views

### Describe the solution you'd like

Some Way to increase the Size of the Font in Table View and in the JSON Views.

### Additional context

On large Screens it is quite difficult to read the content of the Table- or JSON Views.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I'll consider adding it in future.

**Comment by AntonShuvaev** [comment]
I've implemented the ability to zoom in the table view. Zooming JSON views was already in place.
