### ISSUE TITLE
Issue when index or alias contains "_search" in name

### ISSUE THREAD

**Issue by OleksiiYermakov** [AntonShuvaev/elasticsearch4idea#107]
**Describe the bug**
When the index or alias contains in name "_search" the plugin automatically cut all that contains "_search".

**Steps to reproduce**
Create an index or alias for example "demo_search_index"  and try to double-click on it and you will reproduce the issue.

Here is an example with aliases:
<img width="1398" alt="image" src="https://github.com/AntonShuvaev/elasticsearch4idea/assets/60650805/ccc94d88-5a43-401b-b004-833c639f03ef">

**Expected behavior**
Should not cut index name which contains  "_search"

**Environment information:**
- OS: Mac OS
- IDE version: Build #PS-231.9011.38, built on May 17, 2023
- plugin version: 2023.2.1-231
- Elasticsearch or OpenSearch version: elasticsearch:8.4.3

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. Will fix asap.

**Comment by OleksiiYermakov** [comment]
Hello @AntonShuvaev , I saw you updated the plugin. 
After updating the plugin, I can confirm that now an issue is gone and it works correctly.

Thank you for so fast fix of the issue since it blocked me to work with elasticsearch via your plugin. (all my indexes contain "_search_" in names)

Best regards,
Oleksii
