### ISSUE TITLE
The window for building a query disappeared after updating to a `2023.2.2-231` version

### ISSUE THREAD

**Issue by andrey-helldar** [AntonShuvaev/elasticsearch4idea#108]
**Describe the bug**

Previously, when opening an index, there was data in the window on the right, and on the left there was a window for entering a query in JSON format. This window does not exist now. I did not find the right button, how can I turn it on.

Of course, you can separately create a window using the "New Query Console" button, but then it is created completely empty and it becomes necessary to manually enter all the data, starting with the query type and index name.

**Steps to reproduce**
1. Open the Elasticsearch connections window
2. Expand index branch
3. Open the index by double-clicking on it

**Expected behavior**

**Environment information:**
- OS: Windows 11 Pro
- IDE version: 2023.1.2 (PS-231.9011.38)
- plugin version: 2023.2.2-231
- Elasticsearch version: 8.6.1

**Comment by AntonShuvaev** [comment]
Hi, thank you for your feedback.

I intentionally implemented this feature as some users do not use the query console, and it was occupying unnecessary space. However, I agree that there should be a way to open a selected index in the query console. I will add an option to the context menu of the index with shortcut (ctrl + enter) to open the index in the query console.

**Comment by andrey-helldar** [comment]
I can be wrong, but it seems to me that ctrl+enter is an unobvious combination.

I can suggest adding a button to the settings panel.

Our testers use this plugin to send requests to elastic, so the specified combination will not be obvious to them.

In addition to them, I often use the query builder to check the correctness of its formation.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.3. I've added a button to the settings panel as you suggested and also in context menu.

**Comment by andrey-helldar** [comment]
Thank you! 🤝

**Comment by andrey-helldar** [comment]
@AntonShuvaev, I updated the plugin to `2023.2.3-231` version, but I don't see the new button on the panel. Where to find it?

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/10347617/9819968e-f88e-4efa-8f9d-323d506ff4dc)

The Ctrl+Enter hotkey simply removes focus from the table and nothing happens either.

My steps: Double click to open the index. I'm looking for a button to show the builder's console.

**Comment by AntonShuvaev** [comment]
@andrey-helldar, I added buttons `Open In Data Browser` and `Open In Query Console` on the tool window toolbar.

**Comment by andrey-helldar** [comment]
@AntonShuvaev, Understood. Found these items. I thought there are others when I first open the window with a double click.

Thank you!

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/10347617/c8bcba49-abda-4716-a99a-ea2346b5e55a)
