### ISSUE TITLE
Console doesn't automatically open table view

### ISSUE THREAD

**Issue by lookingcloudy** [AntonShuvaev/elasticsearch4idea#111]
**Describe the bug**
On Mac Datagrip:
After closing data grip, reopening, then opening your console and running 
GET /index-01
I simply get JSON text response.  There is no table view or options to change the view.  Not sure how to get back to the table view.

**Steps to reproduce**
Close data grip tabs
Close data grip application
Open data grip
Open "Elasticsearch"
Open default console
Run a GET /index

**Expected behavior**
I would expect the results window to open where I can select table/json and export the data.

**Environment information:**
- OS: Mac
- IDE version:
- DataGrip 2023.1.2
Build #DB-231.9011.35, built on May 16, 2023
macOS 13.4
- plugin version:  2023.2.3-231
- Elasticsearch or OpenSearch version:  8.6.2

**Comment by AntonShuvaev** [comment]
You need to run `GET /index-01/_search` instead of `GET /index-01` to get the table view.

**Comment by lookingcloudy** [comment]
Ok - from a UX perspective - it would be nice to have the same result window regardless, just like datagrip does.  The table view would just be greyed out if there is no table data.

**Comment by lookingcloudy** [comment]
Ok - so running this request:

```
GET /_cat/indices/prod-triton-*?v=true&s=index
```

I now get a table view, but no controls at the top of the page.  I really want this list in raw/json view.
<img width="452" alt="default_–_console___localhost_" src="https://github.com/AntonShuvaev/elasticsearch4idea/assets/5413972/61b30a1c-ad47-49db-82a0-2d7ee7343969">

**Comment by AntonShuvaev** [comment]
The table view is displayed only for the request `GET /index_or_alias/_search`.

**Comment by lookingcloudy** [comment]
What is the view above?  Looks like a table view.  It isn't the raw json returned by the elastic api.

**Comment by AntonShuvaev** [comment]
The table view is displayed only for the search requests. All other requests are displayed in JSON or plain text format depending on the response type. `/_cat/*` API response has compact and aligned text (CAT) format and is displayed in plain text view as it is. If you want to display the response in JSON format, you can use parameter `/_cat/*?format=json`.

**Comment by lookingcloudy** [comment]
Ok - thank you.
