### ISSUE TITLE
Adding the ability to change the document view window

### ISSUE THREAD

**Issue by andrey-helldar** [AntonShuvaev/elasticsearch4idea#114]
### Is your feature request related to a problem?

The problem is only in viewing data - the window is too small

### Describe the solution you'd like

If possible, add the ability to resize the document viewport

### Additional context

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/10347617/232b2b6f-a219-472f-970c-0894d2a85676)

**Comment by AntonShuvaev** [comment]
Hi, thanks for your feedback. I will implement this feature in the next version.

**Comment by andrey-helldar** [comment]
Thank you!

**Comment by andrey-helldar** [comment]
It's works! Thank you!
