### ISSUE TITLE
Connection test failed: com.jcraft.jsch.JSchException: Auth fail for methods 'publickey ,keyboard-interactive'

### ISSUE THREAD

**Issue by Zurich0** [AntonShuvaev/elasticsearch4idea#115]
I try to connect the server with SSH tunnel (must with SSH tunnel), but i got the error message like 
`Connection test failed: com.jcraft.jsch.JSchException: Auth fail for methods 'publickey ,keyboard-interactive'`

**Environment information:**
- OS: MacOS 14.0
- IDE version: #IU-231.8109.175
- plugin version: 2023.2.3-231
- Elasticsearch or OpenSearch version: 7.14.1

**Comment by AntonShuvaev** [comment]
Hi @Zurich0,

Are you using the `OpenSSH config and authentication agent` option in the SSH configuration?
Did you try to connect to the server using the `ssh` command in the terminal? If you can connect to the server using the `ssh` command, you should be able to connect to the server using the SSH tunnel in the plugin.

**Comment by Zurich0** [comment]
> 

Hi @AntonShuvaev ,
I am using OpenSSH_9.3p1, LibreSSL 3.3.6. I can connect the server using ssh command in the terminal, but can not connect the ssh from Elasticsearch plugin. And I try the idea self-contained database tools, it can also connect the server normally.

<img width="710" alt="image" src="https://github.com/AntonShuvaev/elasticsearch4idea/assets/49388136/1a586cf7-ddad-4029-a6c7-c64460ec4800">

**Comment by AntonShuvaev** [comment]
@Zurich0,

Thanks for the details, I will look into it.

**Comment by AntonShuvaev** [comment]
I've added support for keyboard-interactive SSH authentication in 2023.2.4. Please update the plugin and let me know if it works for you.

**Comment by pooyk** [comment]
> I've added support for keyboard-interactive SSH authentication in 2023.2.4. Please update the plugin and let me know if it works for you.

cannot work  @AntonShuvaev 

```
connection test failed: com.jcraft.jsch.JSchAlgoNegoFailException: Algorithm negotiation fail:
algorithmName="server_host_key" jschProposal="rsa-sha2-512,rsa-sha2-256,ssh-ed25519
,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" serverProposal="ssh-rsa,ssh-dss"
```

version 2023.2.4 (2023-07-12)

**Comment by AntonShuvaev** [comment]
@pooyk, I created another issue for this #120.

**Comment by Zurich0** [comment]
> 

It is work for me, thanks~
