### ISSUE TITLE
Store request history and connection details separately

### ISSUE THREAD

**Issue by msmuenchen** [AntonShuvaev/elasticsearch4idea#116]
### Is your feature request related to a problem?

Currently, the settings file `.idea/elasticsearchSettings.xml` contains the cluster configuration (`<option name="clusterConfigurations">`) and the request history (`<option name="requestHistory">`) in the same file.

This can be a concern both for commit-churn (i.e. if you use the request feature, the history pollutes the `git status`), and subsequently for privacy issues (e.g. you connect to a production cluster and search for PII, and then accidentally do a `git commit -a`).

### Describe the solution you'd like

The cluster configurations should each be stored in a separate file (similar to the SQL data sources or run configurations, which are in their own directory), and the history in a separate file as well.

That way, one can decide which configuration(s) to commit, and which to add to a .gitignore (ideally, the plugin would add a .gitignore by default in the folder, including the history file).

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. I'll do it in the next version.

**Comment by AntonShuvaev** [comment]
Implemented in 2023.2.4
