### ISSUE TITLE
"Copy index" modal does not scroll properly

### ISSUE THREAD

**Issue by msmuenchen** [AntonShuvaev/elasticsearch4idea#117]
**Describe the bug**
On low-height screens (tested: MacBook Air 2022 14-inch) the left half of the "Import data" modal that appears upon clicking the "Copy index" menu entry doesn't scroll, but cuts off at the bottom - see below "Bulk request options" here:

<img width="601" alt="image" src="https://github.com/AntonShuvaev/elasticsearch4idea/assets/2284268/4fe6773c-7dd2-4c2d-a54a-a3e6be9bb92b">

**Steps to reproduce**
1. Right-click on an index
2. Select "Copy index to..."

**Expected behavior**
All options are either visible or at least there's a scrollbar.

**Environment information:**
- OS: macOS 13.4.1
- IDE version: PhpStorm 2023.1.3, Build #PS-231.9161.47, built on June 22, 2023
- plugin version: 2023.2.3
- Elasticsearch or OpenSearch version: latest

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix it in the next version.

**Comment by AntonShuvaev** [comment]
Fixed
