### ISSUE TITLE
Failed to identify URLSearch PhraseQuery with spaces 

### ISSUE THREAD

**Issue by pooyk** [AntonShuvaev/elasticsearch4idea#119]
**Describe the bug**
`GET /movies/_search?q=title:"Beautiful Mind"`
The space between Beautiful and Mind cannot be recognized, resulting in the failure of parsing the query statement.

**Steps to reproduce**
Execute any URLSearch PhraseQuery with spaces

**Expected behavior**
Identify spaces correctly.

**Environment information:**
- OS: Apple M1 Max
- IDE version: DataGrip 2023.1
- plugin version: 2023.2.4-231
- Elasticsearch or OpenSearch version: ES 7.17.11

**Comment by AntonShuvaev** [comment]
@pooyk, thanks for reporting the issue. I'll fix it in the next release.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.5
