### ISSUE TITLE
Enable 'ssh-rsa' key support in JSch

### ISSUE THREAD

**Issue by AntonShuvaev** [AntonShuvaev/elasticsearch4idea#120]
After updating the JSch library to the forked version that disables `ssh-rsa` key support by default because it is considered insecure, the plugin is no longer able to connect to servers that only support `ssh-rsa` keys.

The plugin should enable `ssh-rsa` key support by default, as I think plugin users should be able to decide for themselves if they want to use `ssh-rsa` keys or not.

As a workaround before the issue is fixed, you can add `ssh-rsa` to your OpenSSH config file with the `HostKeyAlgorithms` and `PubkeyAcceptedAlgorithms` keywords.

**Comment by pooyk** [comment]
OpenSSH config file  cannot work, and password login cannot pass through the configuration file.
Through the source code, you can know that setting environment variables can solve this problem.

> ```java
> public class JSch {
>   /**
>    * The version number.
>    */
>   public static final String VERSION = Version.getVersion();
> 
>   static Hashtable<String, String> config = new Hashtable<>();
>   static {
>     ......
>     config.put("server_host_key", Util.getSystemProperty("jsch.server_host_key",
>         "ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256"));
>     ......
>    }
> }
> ```

My emergency solution:
add one line  in  [select **Help** | **Edit Custom VM Options**]
`-Djsch.server_host_key=ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa`

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.5
