### ISSUE TITLE
The nested fields view window turns green when searching

### ISSUE THREAD

**Issue by andrey-helldar** [AntonShuvaev/elasticsearch4idea#121]
**Describe the bug**

If you press Ctrl+F or right-click in the opened window while viewing, the window becomes green.

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/10347617/96dbe1f0-f372-491f-9482-a36fcf645a0d)

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/10347617/4084210b-8aee-4629-af95-7ae79b4540b4)

**Steps to reproduce**
1. Open the nested field view window.
2. Press Ctrl+F or right mouse button.

**Expected behavior**
Search by content

**Environment information:**
- OS: Windows 11 Pro
- IDE version: 2023.1.4 (PS-231.9225.18)
- plugin version: `2023.2.4-231`, `2023.2.5-231`
- Elasticsearch or OpenSearch version: 8.8.1

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will look into it.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.6

**Comment by andrey-helldar** [comment]
Thank you!
