### ISSUE TITLE
Shorthand term queries not executing in a similar manner to kibana

### ISSUE THREAD

**Issue by Banashek** [AntonShuvaev/elasticsearch4idea#123]
**Describe the bug**
Shorthand term queries appear to not be sending correctly

**Steps to reproduce**
I have a fairly simple term query I'm attempting through the query console, but it seems to not have an optimization that I see in the kibana query console.

Example query:
```
GET /myindex/_search
{
  "from": 0,
  "size": 50,
  "query": {
    "bool": {
      "must": {
        "term": {
          "my_field": 1
        }
      }
    }
  }
}
```

Note that the above `term` does not explicitly have the name of the field as an object underneath it, but as a simple property.

Compare:
```
"term": {
  "my_field": 1
}
```

vs the ElasticSearch documented:
```
"term": {
  "my_field": {
    "value": "1"
  }
}
```

When the query is sent, this term appears to not be sent at all (I receive _all_ results back).

**Expected behavior**
That the result behavior would be similar to kibana, or that I would be notified that the clause in question would be ignored.

**Environment information:**
- OS: macos `13.3.1`
- IDE version: `2023.2` (build `#DB-232.8660.111`)
- plugin version: `2023.2.5-232`
- Elasticsearch or OpenSearch version: `Elasticsearch 7.1`

**Comment by AntonShuvaev** [comment]
Thank you for reporting this issue. 

Both shorthand and verbose forms of term queries should work identically in Elasticsearch. The format of `"term": {"my_field": "1"}` and `"term": {"my_field": {"value": "1"}}` should give the same result. However, I noticed that you've used `1` (an integer) in your shorthand form and `"1"` (a string) in your verbose form. This could explain why you're seeing different behaviors.

The plugin sends the request JSON body as it is, without any modifications. If you believe the plugin is modifying the JSON request, please provide more details so I can further investigate.
