### ISSUE TITLE
"Illegal character in path at index ... " error when opening an index with a caret symbol in the name

### ISSUE THREAD

**Issue by hoangchu** [AntonShuvaev/elasticsearch4idea#125]
**Describe the bug**

I get an "Illegal character in path at index ..." error when I try to open an index which contains a caret '^' symbol in the name, for example an index named: myindex^2

**Steps to reproduce**

In Elasticsearch create a new index with a name containing a ^ character, for example: myindex^2
Then connect to Elasticsearch using the plugin. Once connected go to the newly created index and double click on it to open.

**Expected behavior**

You'll get an error with an error message similar to this one:
Illegal character in path at index 56: https://elasticsearch-host/myindex^2

**Environment information:**
- OS: Windows
- IDE version: JetBrain Rider 2023.2
- plugin version: 2023.2.5
- Elasticsearch or OpenSearch version: Elasticsearch v7.17.7

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix this in the next version.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.6
