### ISSUE TITLE
Autocompletion for queries on different endpoints

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#127]
### Is your feature request related to a problem?

I noticed that in the REST console, if I change the endpoint (to _count or _update_by_query for example), the query autocompletion does not work. It appears to only works on the _search endpoit.

### Describe the solution you'd like

Have query autocompletion working on every endpoint that supports a query : _count, _update_by_query, _delete_by_query (and may be more I don't know, but you might be able to check if the json has a "query" node and enable autocomplete from that)

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will do it in the next version.

**Comment by AntonShuvaev** [comment]
Implemented in version 2023.2.8
