### ISSUE TITLE
OutOfMemory issue when query matching multiple indices

### ISSUE THREAD

**Issue by spaduret** [AntonShuvaev/elasticsearch4idea#128]
**Describe the bug**
When i build a simple query but `GET` request matching multiple indices (a thousand in my case) the `DataGrip` application is running out of memory.

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/6294984/44933c68-aea1-429d-92ab-3bf894b0e331)

Query example:
```
GET /*customers_*/_search
{
  "size": 10,
  "query": {
    "exists": {
      "field": "scoring.totalScore"
    }
  }
}
```

My best guess is that plugin is trying to grab mapping from all matched indices.
In my case all indices have same mapping.

**Environment information:**
- OS: Windows 10
- IDE version: 2023.2.1
- plugin version: 2023.2.7-232

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will investigate it.

**Comment by AntonShuvaev** [comment]
I improved memory consumption in version 2023.2.8. Let me know if the issue still exists.

**Comment by spaduret** [comment]
The issue is still there.
Whenever i use index pattern `GET /index*/_search` the Rider is freezing and i see a lot of tasks queued:
![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/6294984/f527aa3a-ba63-4993-acc2-f45520763e6b)

**Comment by AntonShuvaev** [comment]
In version 2023.2.9, I've fixed an issue with retrieving index mappings multiple times. This should help with freezing problem.
