### ISSUE TITLE
Toggle auto-query on opening

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#129]
### Is your feature request related to a problem?

I have some indices with very big documents (huge geoshapes). When I open those with either the REST console or the data browser, it immediatly launches a MatchAll query with a size of 50. This is not a big deal as such query will ultimatly complete, but it can slow down my IDE for sometimes more than 5sec for very big documents.

### Describe the solution you'd like

Be able to disable the automatic query on opening per cluster or indices (in my case, as I have multiple indices concerned, I would need to be able to do that with wildcards or juste for the whole cluster).

Or (but it might be more complex and not really needed), implement a system like Kibana "Field filters" that you can set 
when creating a Data View (From Kibana: "Field filters can be used to exclude one or more fields when fetching a document. This happens when viewing a document in the Discover app, or with a table displaying results from a saved search in the Dashboard app. If you have documents with large or unimportant fields you may benefit from filtering those out at this lower level.")

**Comment by AntonShuvaev** [comment]
I've added the ability to open the Data Browser without executing a query. To do this, select the cluster node in the explorer tree and click the 'Open in Data Browser' button.
