### ISSUE TITLE
save config as global.

### ISSUE THREAD

**Issue by twenty-zhang** [AntonShuvaev/elasticsearch4idea#13]
Could cluster config be saved as global? Multiple Idea instances can share cluster configs.
可以保存配置为全局配置吗? 多个idea实例可以共享配置

**Comment by AntonShuvaev** [comment]
Thanks for your suggestion. I will consider it in future releases. As a workaround, you can share clusters configurations between projects by copying the settings file `{projectDirectory}/.idea/elasticsearchSettings.xml`.

**Comment by andynrkri** [comment]
it would certainly be nice to have this feature. It's painful to add clusters in each project when you're working on 10 repos.

**Comment by twenty-zhang** [comment]
@AntonShuvaev Thank for the update.
