### ISSUE TITLE
Please add a header parameters in connection setting

### ISSUE THREAD

**Issue by valdemar1977** [AntonShuvaev/elasticsearch4idea#130]
### Is your feature request related to a problem?

In my case for connect to custom elastic via rest I need to setup a lot of headers that I'm put after -H key in my curl in request 
(ticket, username, password, security.token and so on) 

### Describe the solution you'd like

More headers params in connection settings

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll implement this in the next version.

**Comment by AntonShuvaev** [comment]
Implemented in 2023.2.11
