### ISSUE TITLE
Total size is incorrect in Elasticsearch Inspector

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#131]
**Describe the bug**
Elasticsearch Inspector shows size equal to 1Tb for instances using more than 1Tb

**Steps to reproduce**
Connect to Elasticsearch instance greater than 1Tb, click on it in instances tree, open Elasticsearch Inspector

**Expected behavior**
Show real instance size
```
root@server ~ $ curl 'http://127.0.0.1:9200/_cat/allocation?v'
shards disk.indices disk.used disk.avail disk.total disk.percent host      ip        node
   375        1.8tb     2.3tb    250.9gb      2.5tb           90 127.0.0.1 127.0.0.1 server

root@server ~ $ curl -s 'http://127.0.0.1:9200/_cat/indices?bytes=m' | awk '{s+=$9} END {print s}'
1901010
```
![2023-10-11_15-34-43](https://github.com/AntonShuvaev/elasticsearch4idea/assets/26716666/61fbf530-d84f-4a73-84dd-1de19a5d6fea)

**Environment information:**
- OS: Win10 Pro 19045.3448
- IDE version: 2023.2.2 Build #PS-232.9921.55
- plugin version: 2023.2.11-232
- Elasticsearch or OpenSearch version: 7.10.2

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix this in the next version.
