### ISSUE TITLE
Excuse me, why can't I save the password

### ISSUE THREAD

**Issue by G3792274** [AntonShuvaev/elasticsearch4idea#132]
Excuse me, why can't I save the password？
 

**Environment information:**
- OS: WIN11
- IDE version: IntelliJ IDEA 2023.2.2 RC (Ultimate Edition)
- plugin version:  2023.2.11-232
- Elasticsearch or OpenSearch version: 

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/19231863/cb474619-2e7d-4db0-b649-38f2c163690d)

need to re-enter each time when restart the IDE

**Comment by AntonShuvaev** [comment]
Hi, thanks for reporting the issue. I'm unable to reproduce this. The plugin utilizes the IntelliJ API for persisting sensitive data, which uses KeePass. This can be configured under `Settings | Appearance & Behavior | System Settings | Passwords`. Please ensure that the option `Do not save, forget passwords after restart` is not selected. Also, could you try saving the password in a datasource of the built-in Database plugin and check if it's retained after a restart? Additionally, if you're attempting to save a password in an existing connection, try to create a new one.

**Comment by G3792274** [comment]
Hi [AntonShuvaev](https://github.com/AntonShuvaev), yes you are right ! It's OK  now,Thank you~
