### ISSUE TITLE
Support for elastic 8.10

### ISSUE THREAD

**Issue by NiftyliuS** [AntonShuvaev/elasticsearch4idea#133]
**Describe the bug**

Connecting to elastic search via data-grip warning:
Keep-alive query failed
  Copy
DBMS: Elasticsearch (ver. 7.17.10) Case sensitivity: plain=exact, delimited=exact Driver: Elasticsearch JDBC Driver (ver. 7.17, JDBC4.2) Effective version: UNKNOWN (ver. 8.10) Ping: 121 ms (keep-alive query results in error)  current license is non-compliant for [jdbc].
**Steps to reproduce**

connect with SSL.
Note: Enabling SSL still posts to HTTP instead of HTTPS
**Expected behavior**

connect
**Environment information:**
- OS: windows 
- IDE version: DataGrip 2022.1.5
- plugin version: 2023.2.5-221
- Elasticsearch or OpenSearch version: 8.10.4

**Comment by AntonShuvaev** [comment]
Could you please provide additional details and specific steps to reproduce the issue? The plugin doesn't use the JDBC driver, so I'm a bit unclear about the origin of the message you're encountering.

**Comment by NiftyliuS** [comment]
Thats the error im getting in the intelij plugin... the plugin still works just complains about it.
Ahm steps to reproduce? try to connect to elastic cluster 8.10 or 8.11 with SSL

**Comment by AntonShuvaev** [comment]
It seems you're attempting to connect to Elasticsearch using the built-in Database plugin of DataGrip, which operates through a JDBC driver. This error is not related to my plugin. To use Elasticsearch plugin, please open the `Elasticsearch` tool window and create a connection there.

**Comment by NiftyliuS** [comment]
thank you
