### ISSUE TITLE
Editing data, like removing a field does not get saved. Deletes are working but not edits.

### ISSUE THREAD

**Issue by jacobrillema** [AntonShuvaev/elasticsearch4idea#135]
With the current version, I can no longer edit data inline and save it. I can delete entire documents but edits are not working.  To clarify if I update an existing property and change that field it works. But if I want to remove the property all together it does not get removed. This use to work before.

2023.3.1 (2023-12-05)

DataGrip 2023.3.1
Build #DB-233.11799.296, built on December 11, 2023
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.yaml (233.11799.165)
  org.elasticsearch4idea (2023.3.1-233)
  aws.toolkit (2.1-233)

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will fix this in the next update.
