### ISSUE TITLE
Exclude system/hidden indices/aliases (those starting with a period)

### ISSUE THREAD

**Issue by chrispappas** [AntonShuvaev/elasticsearch4idea#137]
### Is your feature request related to a problem?

The Aliases and Indices lists are overwhelmed by system/hidden items prefixed with a `.` character. This makes it more difficult than it needs to be, to find the items one is interested in. The Advanced config tab allows setting multiple wildcards, but I don't see any way to _exclude_ indices/aliases following a pattern. 

### Describe the solution you'd like

Either offer a checkbox or control to specifically exclude items by a pattern, or support regex in the option inputs (so one can just use `[a-z0-9]+` to only include items beginning with alphanumeric characters).

### Additional context

The Advanced config tab:
![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/4694803/f0b39fb4-ab5c-43d7-b1c0-678197465d51)

What my indices/aliases look like (I haven't even created any indices or aliases yet!):
![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/4694803/3c2405eb-3038-4101-8221-55f0365fde34)

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. I will add the exclude pattern in the next update.

**Comment by AntonShuvaev** [comment]
I found that this feature already exists. You can exclude indices and aliases with a pattern by using a `-` sign. For example, `indexToInclude,-indexToExclude`. In your case, `-.*` should help.

**Comment by chrispappas** [comment]
This is great, thank you for adding it to the hint under the filter input boxes. Really helpful to have it there, I didn't know we could do this. Love being able to filter those out. Thanks for making a really great tool, I use this almost every working day :heart:
