### ISSUE TITLE
IDE freezing when searching large indices

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#138]
**Describe the bug**
Some of my indices contains very big geo_shape data. When opening such indices with the plugin, my IDE sometimes completly freezes. See attached threadDumps_freeze from PhpStorm: [threadDumps-freeze-20240116-105958-PS-233.13135.108-PsiTreeUtil.getChildrenOfTypeAsList-76sec.zip](https://github.com/AntonShuvaev/elasticsearch4idea/files/13948517/threadDumps-freeze-20240116-105958-PS-233.13135.108-PsiTreeUtil.getChildrenOfTypeAsList-76sec.zip)
This is not a big issue as I can always workaround by doing a custom query instead of opening a Data Browser.

**Steps to reproduce**
It can be reproduced with indices where documents contains a very large geo_shape field on my side.

**Expected behavior**
I'm guessing here it's because the IDE is trying to format the whole json which is to big, because the query seems to run fine until the result come back.
If the document is to big to be displayed and formatted, it should probably does what the IDE does for files in such cases: show a message explaining it is to big to be formatted and stop formatting.
Other solutions I see that would be better:
- Collapse such large field by default if possible
- Be able to exclude some fields (like we can do with Kibana Data Views "Field filters") from showing up for queries on some indices (allowing wildcards).

**Environment information:**
- OS: Pop!_OS 22.04
- IDE version: 2023.3.2
- plugin version: 2023.3.3-233
- Elasticsearch or OpenSearch version: 8.11.3

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue! I'll look into it. For now, if you exclude fields in the `Structure` tool window, they'll also be excluded in the `_source` `excludes` of the request. You can also use the `Filter` action to hide fields, but this only works in `Table` and `JSON Hits` views.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.3.4
