### ISSUE TITLE
Every section in every Connection gets expanded on typing and stays expanded when finished

### ISSUE THREAD

**Issue by o-nix** [AntonShuvaev/elasticsearch4idea#139]
**Describe the bug**
I have 5 connections in my ES sidebar. One of the connections has 300+ indices, so I sometimes need to navigate to them quickly.
Previously, if I recall correctly, it was about "IDEA-native" navigation, when you start jumping between matching list items when something has been typed from the keyboard.
However, nowadays, it is a global filter, being applied when you type. This filter somehow includes not only my current active connection under the cursor but all connections at once. That would be fine if all other connections weren't suddenly expanded as well when I am done navigating.

**Steps to reproduce**
* Add more than one connection
* Make sure that every section inside the connections is collapsed (indices/aliases/nodes etc.)
* Start typing on the keyboard to navigate to one of the indices
* Finish navigation or cancel
* Observe that every section inside every connection is now expanded

**Expected behavior**
The previous expanded/collapsed state is preserved OR at least there is a dedicated "Collapse all" button.

**Environment information:**
- OS: macOS
- IDE version: 2023.3.3
- plugin version: 2023.3.4-233
- Elasticsearch or OpenSearch version: opensearch:1.3.2

**Comment by AntonShuvaev** [comment]
I've recently added a filter toggle in the search input field. When this toggle is enabled, searching and filtering apply to all tree nodes, including those that are not expanded. To revert to the previous behavior where the search only applies to already expanded nodes, you can simply disable this filter toggle in the search input field.
<img width="380" alt="Screenshot 2024-02-02 at 18 25 23" src="https://github.com/AntonShuvaev/elasticsearch4idea/assets/25157138/cb7b4cca-cd50-4ff0-ba61-c5018b0cde6b">

**Comment by o-nix** [comment]
@AntonShuvaev thanks, it seems exactly the thing I needed!
I've previously tried to understand what the togglable funnel icon itself means but somehow didn't pay attention.
Please add this info to the tooltip. Also, maybe, it is worth keeping this toggle in the toolbar?
