### ISSUE TITLE
Enable AWS Auth V4 

### ISSUE THREAD

**Issue by Clanver** [AntonShuvaev/elasticsearch4idea#14]
Hi, 

first, im not sure how to mark issues as "enhancements" yet, so sorry! 

I am using the aws elastic search service und connect via AwsAuthV4. 
It would be great to have this option for authenthication as well!

Maybe you can consider it for future versions.

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for suggestion. I've added ability to connect to Amazon Elasticsearch Service with AWS v4 signature.

**Comment by Clanver** [comment]
Thanks! I did not even think you  would consider  it :D. 

Works like a charm! Many Thanks!
