### ISSUE TITLE
Field Filtering No Longer Works Following Update

### ISSUE THREAD

**Issue by benlOXMT** [AntonShuvaev/elasticsearch4idea#141]
**Describe the bug**
Since updating my intelliJ Ultimate to version 2023.3.3 (and I believe I updated the Elasticsearch plugin itself too- am currently on what appears to be the most recent version, version _2023.3.4 (2024-01-25)_), the 'Field Filter' option no longer works dynamically when viewing an index in "Table" view (nb field filtering _does_ still work dynamically for the "Json Hits" view). 

**Steps to reproduce**
View an index (either in REST Console or Data Browser, the issue is present in both) in Table view, click the 'Field Filter' option, select/deselect fields, and observe that nothing happens (all fields remain visible). BUT if in the REST console and I execute a subsequent query (ie click the play button) then the field filtering does take effect. 

**Expected behavior**
Table columns should appear and disappear dynamically according to the selected fields. This is what used to occur prior to the software update. 

**Environment information:**
- OS: macOS Ventura version 13.4 (MacBook Pro, with Apple M1 Pro chip.)
- IDE version: IntelliJ IDEA 2023.3.3 (Ultimate Edition), Build #IU-233.14015.106, Runtime version: 17.0.9+7-b1087.11 aarch64
- plugin version: 2023.3.4 (2024-01-25)
- Elasticsearch or OpenSearch version: 7.17

I've tried restarting intelliJ, but haven't tried bumping up to a newer intelliJ version. Ps thank you for the otherwise very useful software :)

**Comment by AntonShuvaev** [comment]
Thank you for reporting the issue. I'll fix this in the next plugin update. As a workaround, you can use Reload Page (Cmd + R) to apply the filters.

**Comment by benlOXMT** [comment]
> Thank you for reporting the issue. I'll fix this in the next plugin update. As a workaround, you can use Reload Page (Cmd + R) to apply the filters.

Yep that workaround works for me. Nice one 👍
