### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#142]
**Describe the bug**
I'm getting a lot of "Error: Read timed out" when trying to perform some requests that runs fine in any other way.

**Steps to reproduce**
I don't know what exactly is going wrong, all my requests does not fail but some do most of the times, not always. Looks like there is a low timeout on the requests made by the plugin?

**Expected behavior**
Get a result, or be allowed to configure the timeout if it's needed by the plugin.

**Environment information:**
- OS: PopOS! 22.04
- IDE version: PhpStorm 2023.3.2
- plugin version: 2023.3.4-233
- Elasticsearch or OpenSearch version: Elasticsearch 8.12

**Comment by AntonShuvaev** [comment]
Please check and adjust the timeout in the plugin settings (navigate to Settings | Tools | Elasticsearch | Connection Timeout). After the recent update, the timeout now applies to both connection establishment and requests. I'll increase the default value and probably split the request and connection timeouts in a future update.

**Comment by SosthenG** [comment]
Oh sorry my mistake, I didn't know that was already there I was looking in the cluster configuration. Thank you!
