### ISSUE TITLE
Add quick access to data streams

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#144]
### Is your feature request related to a problem?

All data streams backing indices are showing in the top of the "indices" view which is not very practical to use. I can hide them with the advanced configuration but I miss a way to access the whole data stream like there is for aliases.

### Describe the solution you'd like

Add the data streams to the "aliases" view as this is some kind of aliases, or better just add a "data_stream" group for that.
It would be nice to also be able to hide every data_streams (or may be just elastic internal streams like .monitoring, fleet etc) with a quick check box instead of having to create custom patterns

### Additional context

Related to this, I noticed that the custom patterns for indices apply in an unexpected way for data_streams: If I exclude for example `-.*` to hide all data_streams (that should begin with `.ds`) and all elastic internal indices (begin with a dot), I still see the backing indices of my own data_streams because the indices filter seem to work on the data stream name instead of the backing indices name.
So for the example, with this hide filter and if I have a data_stream named "my-stream" for example, I would still see some `.ds-my-stream-2024.02.XXXXX`. If I add `-my-stream` to the filtering rules, then the backing indices all disappears.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I will add this in the future release.
