### ISSUE TITLE
Auto-Completion Feature for inner_hits in has_child and has_parent Queries

### ISSUE THREAD

**Issue by getsolaris** [AntonShuvaev/elasticsearch4idea#146]
### Is your feature request related to a problem?

The lack of auto-completion for the inner_hits feature when using has_child and has_parent queries in Elasticsearch

ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/inner-hits.html

### Describe the solution you'd like

Enhance the query-building experience by introducing an auto-completion or auto-suggestion feature for the inner_hits option. This will enable developers to easily include detailed information from related documents, enhancing the comprehensibility of search results.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I will add it in the next update.
