### ISSUE TITLE
Add action toolbar when querying using search templates

### ISSUE THREAD

**Issue by tomekred** [AntonShuvaev/elasticsearch4idea#147]
### Is your feature request related to a problem?

When querying using _search API there is a toolbar in the results pane. When querying using <index_name>/_search/template
endpoint, this toolbar does not exist.

### Describe the solution you'd like

The toolbar would show up as in standard query results.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I will add it in the next update.
