### ISSUE TITLE
Allow to set a read-only mode

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#15]
Hi,

This in an enhancement suggestion:
It would be great to be able to set an ES connection to a read-only mode, to prevent modifications on production servers.
I have my dev and prod clusters in my connections, even they are explicitly named, we all know that a request can easily be made on the wrong server :smile: 

I was thinking of a simple checkbox to enable the read-only mode (like for databases connection in the database Intellij tool) to prevent all DELETE requests, update, update_by_query, etc.
The best would be to add a confirm dialog when trying to edit/delete something on a read-only server, this way it would still be easily possible to edit prod data while being more secure.

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for suggestion. I have added read-only mode. Also added ability to set background colour in tree view that can be used to distinguish prod/dev clusters too.
