### ISSUE TITLE
Invalid argument exception with OpenSearch Serverless

### ISSUE THREAD

**Issue by CermakM** [AntonShuvaev/elasticsearch4idea#155]
**Describe the bug**
When using the plugin in Goland with AWS OpenSearch Serverless, while the connection is working, I get the following error from the inspection:
```
org.elasticsearch4idea.ey: GET <opensearch endpoint>/_cat/indices/*?format=json&expand_wildcards=open 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
```

This makes it impossible to use the plugin, since I can't even execute es request.

**Steps to reproduce**
Install the Plugin and connect to an OpenSearch Serverless endpoint.

**Expected behavior**
No error occurs.

**Environment information:**
- OS: MacOS
- plugin version: 2024.1.3
- Elasticsearch or OpenSearch version:  2.0.2

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix it in the next version.
