### ISSUE TITLE
Misspelled endpoint for getting stored scripts

### ISSUE THREAD

**Issue by tomekred** [AntonShuvaev/elasticsearch4idea#157]
**Describe the bug**
Plugin suggests `GET /_script/<script-id>` and the correct endpoint is `GET /_scripts/<script-id>` - notice the 's' at the end. The result is error 405 Incorrect HTTP method for uri. Appending the 's' at the end of a phrase '_script' along with script_id returns 200 properly.

**Steps to reproduce**
Begin writing "GET /_script", context menu will show up with said endpoint.

**Expected behavior**
Should point to `GET /_scripts/<script-id>` .

**Environment information:**
- OS: macOS 14.6.1 (23G93)
- IDE version: PyCharm 2024.2.3 (Professional Edition); Build #PY-242.23339.19, built on September 25, 2024
- plugin version: 2024.1.4-242
- Elasticsearch or OpenSearch version: 8.14.3
![get_stored_script](https://github.com/user-attachments/assets/b16574c3-2da6-4874-8e57-b5fff2e572eb)

**Comment by AntonShuvaev** [comment]
Thanks for reporting this. I will fix it in the next version.

**Comment by tomekred** [comment]
Hello Anton,

Could you please share the possible timeline for the next release?

Thanks

**Comment by AntonShuvaev** [comment]
Hi @tomekred, Sorry for the delay! I’ve just released an update with the fix.

**Comment by tomekred** [comment]
Thanks!
