### ISSUE TITLE
Possibility to disconnect from ElasticSearch

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#16]
Disconnect from database sources is available by hotkey Ctrl+F2 or red stop button in database manager.
It would be great if we can disconnect from ElasticSearch server also - for example I'm using SSH tunnel to connect to server and connection hangs after logout until PhpStorm is closed.

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for your suggestion. It will be released in 0.4.0.
