### ISSUE TITLE
Convert unicode symbols

### ISSUE THREAD

**Issue by alphamikle** [AntonShuvaev/elasticsearch4idea#17]
Hello!
I'm very thankful to you for your plugin! I wish u can help with a small problem - Cyrillic symbols are encoded in Unicode and can't be read in "Text" view mode:
![image](https://user-images.githubusercontent.com/29115406/96998725-a6777600-153c-11eb-8e0d-11c538d96855.png)
But in "Table" view mode this data was print correctly.

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for reporting this issue. It will be fixed in 0.4.0.
