### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#18]
I got an error while trying to sort output by any column

![2020-11-09_09-26-40](https://user-images.githubusercontent.com/26716666/98507077-ef823680-226d-11eb-8bac-f2100a588ece.png)

Windows 10 Pro 64
PhpStorm 2020.2.3 Build #PS-202.7660.42, built on October 16, 2020
Plugin version 0.4.0
ElasticSearch 6.8

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for reporting this issue. Update 0.4.1 with fix is available now.
