### ISSUE TITLE
Easier Iindex deletion

### ISSUE THREAD

**Issue by patrickkusebauch** [AntonShuvaev/elasticsearch4idea#19]
This is a great plug-in, the only issue I had thus far is with deleting indexes. It just takes too long, especially if you need to delete multiple indexes or even delete all indexes. I can see 3 ways to make it easier.

1) Context menu option on the level of connection to "Delete all indexes". Here a confirmation box to explicitly write "DELETE" would make sense IMHO.
2) Context menu option while having multiple indexes selected to "Delete". Here a Yes/No Confirmation box would be OK.
3) Change the confirmation box for single deletion from writing "DELETE" to Yes/No. I do not know about your experience, but for me, I resort to copy&paste when I have to delete more than one index anyway. It just slows me down.

What do you think about those? I would be open to helping you out if you think they are a good idea, but do not have the time to develop them.

**Comment by AntonShuvaev** [comment]
Hi,

I have added the ability to delete multiple indices at once. Also, confirmation by typing "DELETE" is replaced by Yes/No. It will be available in 0.4.2.

**Comment by patrickkusebauch** [comment]
@AntonShuvaev probably a bug in the new version? Where the bold text is not formatted correctly?
![Screenshot from 2020-12-01 07-39-13](https://user-images.githubusercontent.com/1620948/100705955-665faa80-33a8-11eb-9252-755b6ab05cf8.png)

**Comment by AntonShuvaev** [comment]
@patrickkusebauch Thanks for the feedback. This will be fixed in the next release.
