### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by NetwarSystem** [AntonShuvaev/elasticsearch4idea#2]
Hello,

Our Elasticsearch cluster is protected with Search Guard. This means we have SSL on port 9200 and this plugin cannot connect.

What would be required to add SSL support?

**Comment by AntonShuvaev** [comment]
Hello,

Thanks for your suggestion. I am going to add SSL support in the next release, probably in a few days.

**Comment by AntonShuvaev** [comment]
@NetwarSystem ,

I have added SSL support. In the "Add Elasticsearch cluster" dialog you need to specify the path to your PKCS#12 truststore with CA certificate. And if you use client certificate and private key you also need to specify the path to PKCS#12 keystore with them. If you use a format other than PKCS#12 you can convert it.

**Comment by NetwarSystem** [comment]
Anton - thanks for noticing this, but I'm not at all sure what to do next.

Simply putting https in instead of http in the first dialog panel doesn't work.

My cluster has a self signed certificate and matching host.key & host.pem for each system. There is a superuser pair as well. This seems like it is somewhere close to what is needed:

https://stackoverflow.com/questions/25247850/how-to-create-pkcs12-truststore-using-openssl

But this is all I have in terms of user access rather than systems:

> clients:
>   - name: tundra
>     dn: CN=tundra.netwarsystem.com,OU=CA,O=Netwar System,DC=netwarsystem,DC=com
>     admin: true

Possessing the pem & key are all I need to remote access. Any hint on where to go next? I'll write this up and post to Search Guard's forums once I get it working ...

**Comment by AntonShuvaev** [comment]
@NetwarSystem 

You need to update the plugin to 0.1.5 version. There is an SSL tab in 'Add Elasticsearch cluster' dialog where you should specify path to .p12 file. You can convert your pem and key to PKCS#12:
 https://mkyong.com/linux/ssl-convert-pem-and-private-key-to-pkcs12/

I'm not sure if there is a difference between Search Guard and Elasticsearch SSL settings. I used [Encrypted communication](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html#_encrypted_communication) guide.

**Comment by leberknecht** [comment]
Hello, 
i have a `.p12` file, but i cant select the containing folder on the UI, the "OK" button stays greyed-out when i select the folder. Am i missing something? What are the conditions for the truststore folder?

**Comment by AntonShuvaev** [comment]
Hello @leberknecht, 

Thanks for reporting. I've found that on Windows it is not possible to select any file due to mistake in file extension filter. It will be fixed in the next release.

**Comment by leberknecht** [comment]
Im actually on Linux but if you are on Mac, then maybe the problem is of the same nature :)

**Comment by AntonShuvaev** [comment]
@leberknecht, the bug has fixed in 0.1.8 which is already available for update.

**Comment by leberknecht** [comment]
Ahoi, i now can select the p12 cert, but when i test the connection im getting 
```
Conection test failed: elasticsearch-master.prod.svc.cluster.local:9200 failed to respond
```
To ensure that its correct, i changed the port, which does result in a different error:
```
Conection test failed: Connect to elasticsearch-master.prod.svc.cluster.local:9201 [elasticsearch-master.prod.svc.cluster.local/10.15.247.169] failed: connect time out
```
so it seems that the TCP connection does work, so im wondering if there is anything else i can do to get more debugging information?

**Comment by leberknecht** [comment]
i was actually providing the CA cert, where i should have used a client-cert-signed-by-ca
