### ISSUE TITLE
Better support for _source and fix filter_path

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#20]
Hi,

I tried to make a request to only get a few fields of my documents and it seems that the table view always shows all the fields even if we only request a few with the `_source` parameter (the column are just empty with `unset`)
I tried to limit the fields with the `filter_path` parameter, it works fine with the text view but with the table view it results with a `java.lang.NullPointerException` when running the query.

Could it be possible to support limiting the fields to show in the table view?

Thanks!

**Comment by AntonShuvaev** [comment]
Hi,

I have fixed limiting fields by `_source` in the table view. It will be available in 0.4.2. `filter_path` remains unsupported in the table view as it is more difficult.
