### ISSUE TITLE
insecure SSL not working

### ISSUE THREAD

**Issue by netchose** [AntonShuvaev/elasticsearch4idea#22]
hi,

i can't connect : same message and same test than this issue : 

https://github.com/AntonShuvaev/elasticsearch4idea/issues/9#issue-678483348

even with self-signed checked, 

thanks

**Comment by AntonShuvaev** [comment]
Hi,

Can you provide more details? Also, you can take a look at documentation https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html
because HTTP client in plugin is configured in the same way as there.

**Comment by netchose** [comment]
Hi Anton,

-  i can connect to my ES cluster without problem with Pycharm http client:
https://www.jetbrains.com/help/pycharm/http-client-in-product-code-editor.html
and with Python library "Requests"  and with others external tools.
your plugin is the only tool i can't use to connect to the cluster

maybe i can provide you log file . if you can tell me the location

thanks for answer

**Comment by AntonShuvaev** [comment]
How do you specify certificate and in what format?

**Comment by netchose** [comment]
i will check asap. if it can be useful i will see to provide a docker file

**Comment by AntonShuvaev** [comment]
Do you configure certificates in https://www.jetbrains.com/help/idea/settings-tools-server-certificates.html when using Pycharm http client? My plugin doesn't use them. You need to specify certificate in truststore in JKS or PKCS12 format.

**Comment by AntonShuvaev** [comment]
I will add support for [server certificates](https://www.jetbrains.com/help/idea/settings-tools-server-certificates.html) in the future release.

**Comment by AntonShuvaev** [comment]
@netchose 

I released an update. Your problem must be resolved now.

**Comment by netchose** [comment]
Hi Anton,

it works very well :)

big thanks for your work !
