### ISSUE TITLE
All fields hidden in table view when type is "_doc"

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#24]
Hi,
Since the last update (0.7.0) that allows to hide some fields, all my fields are hidden but I can't find a way to show them.
The only fields I see in the table view are the ES functional fields (prefixed by "_").
If I open the "Index Structure" menu, those are also the only fields I can see.

![image](https://user-images.githubusercontent.com/22033159/105025468-41e98b80-5a45-11eb-8a0e-3bc74d3e0172.png)

On text view I can see all my fields of course, but I can't find a way to show them in the table view.

EDIT : After further investigations, I have the issue with all legacy indexes where my type is "_doc" (as it was the convention at the time, when types were going to be removed). With other indexes that have an other type (for example I have an index with a "destination" type), it works. So clearly an issue with types having the name "_doc".

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for reporting this bug.  The update 0.7.1 with the fix will be available soon.
