### ISSUE TITLE
http://10.0.0.1:8200/1809568727 Cannot connect

### ISSUE THREAD

**Issue by xiaoxiaopingzi** [AntonShuvaev/elasticsearch4idea#25]
I have es url like this, http://10.0.0.1:8200/1809568727, but the prompt invalid http host.

Could it be possible to  considered compatibility with this situation?

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting this issue. It will be fixed in the next bugfix soon.

**Comment by AntonShuvaev** [comment]
Fixed in 0.7.2
