### ISSUE TITLE
Multi search JSON error

### ISSUE THREAD

**Issue by twenty-zhang** [AntonShuvaev/elasticsearch4idea#27]
Multi search function worked fine but this is a error showed in JSON edit box.
"JSON standard allows only one top-level value."

[multi search API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-multi-search.html#search-multi-search)
plugin version: 0.7.2
idea version: 2020.3.2

**Comment by AntonShuvaev** [comment]
Thanks for reporting issue. Fixed in 1.0.0
