### ISSUE TITLE
All cluster went down because I miss-clicked on order by _id

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#28]
Hi,

Just had a major issue with this. My whole ES prod cluster went down because I just miss-clicked on the "_id" column (which has for consequence to sort by it).
Just tried again in dev to see if I can reproduce and yes, my dev ES crashed after doing that.
I might have a config issue too, as in dev my cluster only crashed once, after that, when I tried again, I just had a CircuitBreakingException as a result : `java.util.concurrent.ExecutionException: CircuitBreakingException[[fielddata] Data too large, data for [_id] would be ...`

I will investigate on why my whole cluster crashed for that, but anyway the sort on the _id field **should be disabled** as the doc clearly states this field should not be used to sort: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 
Thanks, for reporting an issue. Sorting by id definitely should be disabled. I will do it in the next update.

**Comment by AntonShuvaev** [comment]
Fixed in 1.0.0
