### ISSUE TITLE
1.0 regressions ?

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#29]
Hi,

Just updated to the 30 days trial of the 1.0 version and noticed some regressions:
- No longer have the requests history (that was useful!)
- Can no longer launch requests to see only aggregations: seems like even in text view mode, only hits are shown. When launching a request with a size of 0 and one aggregation, I get an empty array as a result `[]`

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for your comments, totally agree with that. Will be fixed ASAP.

**Comment by AntonShuvaev** [comment]
Fixed in 1.1.0

**Comment by SosthenG** [comment]
Hi,
Just noticed another regression, I can only launch search requests, I cannot find a way to launch get or delete request (I do remember that being possible with a previous version, with the possibility of choosing the HTTP method with a dropdown).
_search requests being the most useful with this plugin, it makes sense to use them by default, but being able to launch other requests would be nice too.

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

I split into two different functionalities: search and any REST request. There are buttons "Open Data Browser" and "Open REST Console" on toolbar.

**Comment by SosthenG** [comment]
Thanks, didn't see that, my bad !
