### ISSUE TITLE
Query URL encoding issue

### ISSUE THREAD

**Issue by j4r3kb** [AntonShuvaev/elasticsearch4idea#3]
I'm trying to make a request `GET /_cat/indices?h=index`
getting following error:
```
{
    "error": "Incorrect HTTP method for uri [/_cat/indices%5C%3Fh=index] and method [GET], allowed: [POST]",
    "status": 405
}
```

curl works just fine `curl -XGET "localhost:9200/_cat/indices?h=index"`

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting. I've fixed this issue. You should update plugin to version 0.1.5.
