### ISSUE TITLE
Intellij eating whole memory when resultset is very large

### ISSUE THREAD

**Issue by mt3o** [AntonShuvaev/elasticsearch4idea#30]
![image](https://user-images.githubusercontent.com/158868/112954933-2e425b80-913f-11eb-9884-e6a453cde23c.png)

I executed a query over my ES index, sorting by field (in UI, not query) that's pretty long (sometimes 100mb+) and the action caused IntelliJ to eat 32GB of RAM. 
Such action should be prevented from eating whole RAM :-)

**Comment by AntonShuvaev** [comment]
Thanks for reporting an issue. I will take a look at it. As a workaround, you can decrease the page size or select only necessary fields.

**Comment by AntonShuvaev** [comment]
Probably it was due to memory leak. Must be resolved in 2022.1.7
