### ISSUE TITLE
Cant see onced hiden fields, whoes name starts with "_", like "_id"

### ISSUE THREAD

**Issue by SoaQa** [AntonShuvaev/elasticsearch4idea#33]
Hello!
When i hiding fileds in table mode, query changes, but if i hide fileds starts with "`_`", like field "_id" or "_index", they hiding, but query does not changes and i cant see this fields again. How i can unhide them?  
Reconnect and restart IDE is not helping.
![image](https://user-images.githubusercontent.com/42070578/120475577-32466000-c3b2-11eb-80ab-7d1c15ff7833.png)

**Comment by AntonShuvaev** [comment]
Hello!

You can show/hide fields in the Index structure view (Cmd 7 or Cmd F12). Select the necessary fields and press Space button. 
Here is some [documentation](https://plugins.jetbrains.com/plugin/14512-elasticsearch/custom-pages/592).

**Comment by SoaQa** [comment]
Добрый день, хорошо. Просто неожиданное поведение, когда ты делаешь запрос
с "_source": {"include" : ["name"]}, эти поля скрываются, а когда из
запроса это убираешь они не появляются обратно🙀

ср, 2 июн. 2021 г. в 15:04, Anton Shuvaev ***@***.***>:
