### ISSUE TITLE
ssh auth failed.

### ISSUE THREAD

**Issue by glight2000** [AntonShuvaev/elasticsearch4idea#34]
ssh auth failed with the correct UserName and Password.

**Comment by AntonShuvaev** [comment]
Hi,

Do you see an error after clicking the button "Test SSH Connection"? If yes, could you provide an error message? You can hover on the error to see full message.

**Comment by glight2000** [comment]
> Hi,
> 
> Do you see an error after clicking the button "Test SSH Connection"? If yes, could you provide an error message? You can hover on the error to see full message.

Here is message:
`Connection test failed:JSchException:Auth Cancel`

**Comment by AntonShuvaev** [comment]
@glight2000, thanks. I fixed this issue in 1.4.1. It will be available soon.

**Comment by glight2000** [comment]
It works.
Thanks.
