### ISSUE TITLE
How to insert/delete multiple documents by one query/action?

### ISSUE THREAD

**Issue by glight2000** [AntonShuvaev/elasticsearch4idea#36]
How to insert/delete multiple documents by one query/action?

**Comment by AntonShuvaev** [comment]
Actions for adding and deleting multiple documents are not supported yet. I will consider adding it in a future release. Now the only option is to use [`Bulk API`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) request.

**Comment by AntonShuvaev** [comment]
Now it is possible to create, delete or edit multiple documents in table. Editing multiple documents is also possible in dialog window. So I close this issue.
