### ISSUE TITLE
Feature request: Ability to copy data from columns?

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#37]
Hi,

I think it would be nice to be able to copy data directly from the table view.
I don't know anything about idea plugins so it might not be possible.
Actually when I try to copy from the table results I get something like "org.elasticsearch4idea.hS@3f904cd7" instead of the actual value. Right now I was trying to copy an entire column content but was not able to do so, instead I got a list of "org.elasticsearch4idea...".
A nice alternative could be to have a button to download the results as csv.

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, @SosthenG,

Good idea! I will do it.

**Comment by AntonShuvaev** [comment]
Released in 1.5.0
