### ISSUE TITLE
elasticsearch Content-Type header [text/plain; charset=UTF-8] is not supported

### ISSUE THREAD

**Issue by nkajic** [AntonShuvaev/elasticsearch4idea#38]
Hi @AntonShuvaev 

in latest version 1.4.1 i am unable to browse data in Data browser.

However after downgrade to 1.4.0 all works fine.

PhpStorm 2021.2

I resolved this problem by downgrading. Thanks for your plugin. I am writing this ticket just to inform you if someone else is having this problem also.

Thx,
N

**Comment by AntonShuvaev** [comment]
Hi @nkajic,

Does your index name contain `_cat` substring? I added `text / plain` content type for requests with path containing`_cat` for` _cat APIs` but forget that an index name can contain this substring.

**Comment by DongchaoXu** [comment]
Hi, @AntonShuvaev, same issue to me with the index name xx_category.

**Comment by AntonShuvaev** [comment]
@DongchaoXu 

Thanks for the details. The fix will be soon.

**Comment by AntonShuvaev** [comment]
Fixed in 1.4.2
