### ISSUE TITLE
Settings are not transferred to another computer

### ISSUE THREAD

**Issue by andrey-helldar** [AntonShuvaev/elasticsearch4idea#40]
PhpStorm is configured to upload the configuration to the GitHub repository.

I created a connection setting by choosing "settings level - global".

On my local machine, opening different projects, I see a global setting.

But on another computer it won't boot. That is, the plugin saves the configuration for global use within a single computer.

It is not comfortable

![image](https://user-images.githubusercontent.com/10347617/130317744-3db1e23e-d7be-4b41-adde-f4c99b2db971.png)

**Comment by AntonShuvaev** [comment]
Hi @andrey-helldar, I will fix this in the next release.

**Comment by andrey-helldar** [comment]
@AntonShuvaev, thank you! 😊

**Comment by AntonShuvaev** [comment]
Fixed in 1.5.1
