### ISSUE TITLE
Invalid update format for Bulk API export

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#41]
![image](https://user-images.githubusercontent.com/26716666/131314121-df71c88d-a0c6-4f41-a6d3-02e095cbba16.png)

Second line of file should include not only the document but an object with property "doc"

![image](https://user-images.githubusercontent.com/26716666/131314385-d895538b-17d0-4afc-a4d7-c94a72040d71.png)

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting this bug. Will be fixed in the next update.

**Comment by AntonShuvaev** [comment]
Fixed in 1.5.1
