### ISSUE TITLE
Multi node connection doesn't seem to work

### ISSUE THREAD

**Issue by cakarlen** [AntonShuvaev/elasticsearch4idea#43]
I have a 3 data node ES cluster with my configuration looking like this:

![image](https://user-images.githubusercontent.com/33635487/131507994-7fbe14be-9d21-402e-80e1-45a30455df7e.png)

If I take the first node offline in the URL list, I cannot communicate with ES by doubling clicking on my cluster or by manually refreshing until I cut+paste the "down" data node and put it last in the list (which will make it check the next node in the list).

**Comment by AntonShuvaev** [comment]
Hi! The problem was probably because of a missing connection timeout. I have added configuration for connection timeout and set 5 seconds by default. The fix will be released soon.

**Comment by AntonShuvaev** [comment]
Fixed in 1.5.1. Could you please check that connection to multiple nodes is working as expected?

**Comment by cakarlen** [comment]
Seems to work! Thank you for your help.
