### ISSUE TITLE
No result window after update to PhpStorm 2021.2.1

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#44]
Hello,

I'm having a strange bug: I don't see any result for my queries after updating my phpstorm to 2021.2.1 (on linux, using manual archive downloaded from jetbrains).

My saved cluster are there, I can open a REST console but when I launch any request, I can see the "Performing request" loader at the bottom of the IDE, but after that I don't see the result anymore: it uses to split the window in half, left for the query and right for the results before I updated I think.

It's the same for everything, trying to show cluster stats, health or anything gives me an empty window.
I don't even have the editor config icon on the right (see attached capture).
![Nothing in the result view](https://user-images.githubusercontent.com/22033159/131843910-72467506-40fd-4bc3-ab2e-80de3af86938.png)

Launching the same request with curl or the phpstorm internal http client works fine, so the issue is not coming from my cluster.
I tried to uninstall and reinstall the plugin, remove and re-add my cluster, still happening.
I don't see anything in the PhpStorm logs when using the plugin.

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

Could you try on the new version 1.5.1?

**Comment by SosthenG** [comment]
Yes it solved the issue, thank you!
