### ISSUE TITLE
Add autocompletion for aggregation queries

### ISSUE THREAD

**Issue by cakarlen** [AntonShuvaev/elasticsearch4idea#45]
It'd be great to have autocompletion for writing agg queries in the data browser

**Comment by cakarlen** [comment]
@AntonShuvaev hi! Is this still a planned feature?

**Comment by AntonShuvaev** [comment]
Hi @cakarlen,

Yes. I'm doing the refactoring to be able to easily extend autocomplete for aggregations and other APIs. I'm planning to release autocomplete for aggregations API to the end of December.

**Comment by cakarlen** [comment]
Awesome! Thanks for your hard work

**Comment by AntonShuvaev** [comment]
Released in 2022.1
