### ISSUE TITLE
HTTP method dropdown in REST query console is truncated

### ISSUE THREAD

**Issue by kraju** [AntonShuvaev/elasticsearch4idea#46]
Seeing what kind of HTTP method is used is quite crucial for manual REST operations, however on Intellij 2021.2.2 with plugin 1.5.1 (running on Ubuntu Linux), method dropdown is truncated:

![image](https://user-images.githubusercontent.com/1223522/134656232-b468577b-6cb3-4640-be0d-35f25949535c.png)

**Comment by AntonShuvaev** [comment]
Fixed in 1.6.0
