### ISSUE TITLE
Elasticsearch plugin window does not follow Intellij editor theme

### ISSUE THREAD

**Issue by kraju** [AntonShuvaev/elasticsearch4idea#47]
Using Intellij 2021.2.2 with plugin 1.5.1, with editor theme set to High Contrast (and dark IDE theme), seems like everything follows this pattern, but Elastisearch plugin ignores the editor theme:

![image](https://user-images.githubusercontent.com/1223522/134657671-798cef92-670a-4330-98e2-bf4121a53e59.png)

**Comment by AntonShuvaev** [comment]
Fixed in 1.6.0
