### ISSUE TITLE
Add index templates to indices/aliases/nodes list

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#48]
GET /_template for ElasticSearch 6.*
GET /_index_template for ElasticSearch 7.*

**Comment by AntonShuvaev** [comment]
Added in 1.6.0

**Comment by evgenyvolferts** [comment]
Context action is not useful at all :(

**Comment by AntonShuvaev** [comment]
Could you describe the use case and how you would like to see this feature? I'll try to do it in the next release.

**Comment by evgenyvolferts** [comment]
I will be glad to!

The main idea is to be able to get a list of templates and quickly get templates properties.

I would like to see a new item "templates" in the list along with indices/aliases/nodes with template names as subitems. Double clicking on the template name could send a request GET /_index_template/<template_name> showing JSON with template properties (as it is shown now with just /_index_template request).

Thanks in advance

**Comment by AntonShuvaev** [comment]
Thanks, I've got it. It will be done in the next release.

**Comment by AntonShuvaev** [comment]
Added in 1.7.0
