### ISSUE TITLE
Cannot work with large results

### ISSUE THREAD

**Issue by ostrolucky** [AntonShuvaev/elasticsearch4idea#49]
I wanted to use this plugin to export large index into CSV, having more than 1 billion results. However, when I increase page size beyond 10000, ES complains that result window is too large.

![2021-10-26_17-37-03 (1)](https://user-images.githubusercontent.com/496233/138913400-d6d548ec-33d7-4d8a-bcab-49ad6116c75d.gif)

Plugin should paginate these results and load data in batch, not attempt to request everything at once.

**Comment by AntonShuvaev** [comment]
Hi! I will consider adding paginating with `search_after` to export as Elasticsearch doesn't allow search more than `index.max_result_window` (10000 by default).

**Comment by AntonShuvaev** [comment]
I have added the option to export all documents with Scroll API.

**Comment by ostrolucky** [comment]
Thanks! I was thinking this would be integrated into core transparently, but this way it also seems working. Good to see you respond to issues in timely manner, it gives me affirmation that it was good decision to pay for the licenses!

I see there is still one related problem to this, but I'll create separate issue for it :)
