### ISSUE TITLE
Quick jump to a column

### ISSUE THREAD

**Issue by ostrolucky** [AntonShuvaev/elasticsearch4idea#50]
It's difficult to find the column you are interested in with this plugin. With MySQL plugin or other stock IntelliJ plugins, on hitting CMD+F12, it shows list of fields, similarly as this plugin shows structure. However, while stock plugins jump to a colum when selecting field from this list, this plugin doesn't. That makes it very confusing for me and difficult to find the information in row I'm looking for.

![2021-10-26_18-11-45 (1)](https://user-images.githubusercontent.com/496233/138918947-47d366a2-b726-4d65-8f06-1c7cb389ad8c.gif)

**Comment by AntonShuvaev** [comment]
Good point. I will fix it in the next release.

**Comment by AntonShuvaev** [comment]
Added in 1.7.0

**Comment by ostrolucky** [comment]
thanks, works like a charm!
