### ISSUE TITLE
Table-view is missing columns on one index

### ISSUE THREAD

**Issue by leberknecht** [AntonShuvaev/elasticsearch4idea#51]
Hi,
for one of my indices, the table-view for the results doesnt work (on the other indices it works like charm). It shows only the build-in fields but is missing all the fields from `_source`
Here is the view as json-hits:
![image](https://user-images.githubusercontent.com/1165177/139019282-6cd47d79-0f95-4869-a5a3-9cb62734f2d6.png)
here is the table-view:
![image](https://user-images.githubusercontent.com/1165177/139019352-99473705-2b1c-41a6-a117-5fe802a70b49.png)

Is there anything i missed? It shows fine with kaizen, 
Here are the `_settings`: 
```
{
  "reputation_dev_searches": {
    "aliases": {},
    "mappings": {
      "properties": {
        "created_at": {
          "type": "date"
        },
        "hit_count": {
          "type": "integer"
        },
        "institution_id": {
          "type": "keyword"
        },
        "search_id": {
          "type": "keyword"
        },
        "updated_at": {
          "type": "date"
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1635260269618",
        "number_of_shards": "1",
        "number_of_replicas": "1",
        "uuid": "IovQChmDQYird8jJLgh_WA",
        "version": {
          "created": "7080099"
        },
        "provided_name": "reputation_dev_searches"
      }
    }
  }
}
```

**Comment by AntonShuvaev** [comment]
Hi! This is a bug. I will fix it ASAP

**Comment by AntonShuvaev** [comment]
Fixed

**Comment by leberknecht** [comment]
Can confirm, works as-expected now. Thank you :)
