### ISSUE TITLE
Request: Read AWS credentials + profiles from  ~/.aws/credentials

### ISSUE THREAD

**Issue by drichelson** [AntonShuvaev/elasticsearch4idea#54]
I work in an environment where AWS credentials get cycled regularly, so manually pasting them in every few hours is a hurdle that makes this tool not worth using for now. It would be awesome if this tool allows the selection of a profile and the creds are read from `~/.aws/credentials` (this is a standard location used by aws tools and libraries)

**Comment by AntonShuvaev** [comment]
Good suggestion! I will support this in the next update.

**Comment by AntonShuvaev** [comment]
Added in 1.7.1
