### ISSUE TITLE
Change export csv separator

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#56]
Hi,

I tried to export some documents with an array field inside but the commas used to separate array values in a field are messing with the csv formatting, making the export of documents with array fields unusable.
Considering this I think the default csv separator should not be a comma and adding the possibility to change it manually would be nice.

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting the issue. I have added the escaping of a comma in an array by wrapping the value in double quotes. Also, added  Delimiter-separated values (DSV) extractor where you can specify the delimiter.
