### ISSUE TITLE
Size: 0 is ignored after switching view

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#59]
Hi,

Very small issue.
I noticed that the "size" parameter of a search query is ignored after switching view when set at 0.

How to reproduce:
- Make a search with a `"size": 0`
- The current view (any) your looking at will have no result => OK
- Switch to any other view (table, hits or response): you can see the hits besides the size being 0 => KO

Thanks!

**Comment by AntonShuvaev** [comment]
Fixed in 2022.1
