### ISSUE TITLE
Elasticsearch dsl input autocompletion

### ISSUE THREAD

**Issue by li1234yun** [AntonShuvaev/elasticsearch4idea#6]
Hello, Thank you for providing the good elasticsearch plugin! I just some propose for improving the plugin for autocomplete. This is only my advice, it's up to you!

Thank for your work!

**Comment by AntonShuvaev** [comment]
Hello, Thanks for your feedback! Good suggestion. Now I'm working on pagination and sorting in the table view. After that, I'm going to add autocompletion.

**Comment by AntonShuvaev** [comment]
Done
