### ISSUE TITLE
Confirm delete window while removing symbols in query input 

### ISSUE THREAD

**Issue by kolybelkin** [AntonShuvaev/elasticsearch4idea#61]
Steps to reproduce:

1. Find something using a query
2. Browse found data and select any line (one click on it)
3. Click in input text to change the query
4. Type Backspace button to remove a part of the query
5. Confirm delete windows appears whereas I do not want to remove any documents, I just want to modify the query

The behaviuor has appeared recently after an update.

**Comment by AntonShuvaev** [comment]
Hi, thanks for reporting the issue. It will be fixed in the next update.

**Comment by kolybelkin** [comment]
Hi, could you please advise what the estimations for the date on next release are?

**Comment by AntonShuvaev** [comment]
Early next week

**Comment by Aroks25** [comment]
same issue

**Comment by AntonShuvaev** [comment]
Fixed in 2022.1
