### ISSUE TITLE
ssh tunnel doesn't ask for, nor allow a specific remote host

### ISSUE THREAD

**Issue by apatrida** [AntonShuvaev/elasticsearch4idea#62]
The SSH tunnel option has the SSH host itself, and your connection to the tunnel (localhost:{port}) but no where does it ask for the remote host that the connection should be forwarded to.

For example with a SSH tunnel:

```
ssh ubuntu@remotehost.whatever.com -L 10443:eshost.private.whatever.com:443 -N
```

I would connect to localhost:10443 as my connection, but notice I need two other hosts specified.  The plugin does not have this option.

**Comment by AntonShuvaev** [comment]
Hello,

Could you try to specify `eshost.private.whatever.com:443` in URL field on the General tab and `ubuntu@remotehost.whatever.com` in Host field on the SSH tab?
