### ISSUE TITLE
Login to AWS OpenSearch with credentials file is not working

### ISSUE THREAD

**Issue by alex-karo** [AntonShuvaev/elasticsearch4idea#63]
Throws an error when tries to connect

![image](https://user-images.githubusercontent.com/17811999/150744276-8d340067-a1a4-46c8-bbd2-a171f065254a.png)

```
Error: com.amazonaws.SdkClientException: To use assume role profiles the aws-java-sdk-sts module must be on the class path.
```

IDE:
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Runtime version: 11.0.13+7-b1751.21 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

OS:
Model Name:	MacBook Pro
Chip:	Apple M1
System Version:	macOS 11.6 (20G165)
Kernel Version:	Darwin 20.6.0

**Comment by AntonShuvaev** [comment]
I have added `aws-java-sdk-sts`, so login to AWS should work now in version 2022.1. Let me know if you still have issues.
