### ISSUE TITLE
Add support for https with oauth2 connection

### ISSUE THREAD

**Issue by Hronom** [AntonShuvaev/elasticsearch4idea#65]
Please provide possibility to send requests trough https connection with additional oauth 2.0. 
There situations when access to prod allowed only trough proxy that use oauth 2.0 or something else.
Please provide additional configuration parameters to build such connections.

**Comment by AntonShuvaev** [comment]
Good suggestion! I will consider adding this in the future update.

**Comment by AntonShuvaev** [comment]
@Hronom, can you give more details on your use case. What grant type do you use? I'm going to support password credentials and client credentials grant types.

**Comment by Hronom** [comment]
@AntonShuvaev this is what used in postman to connect
![image](https://user-images.githubusercontent.com/429993/154871138-6ef050cd-7620-4940-a17f-bf9a44731f2d.png)

**Comment by AntonShuvaev** [comment]
Added in 2022.1.3. Let me know if have any issues.
