### ISSUE TITLE
elasticsearch 8.0.0

### ISSUE THREAD

**Issue by ppap6664180** [AntonShuvaev/elasticsearch4idea#67]
not supported elasticsearch 8.0.0 version,required http_ca.crt

**Comment by AntonShuvaev** [comment]
Can you describe your problem in more detail? I have run Elasticsearch 8.0 in docker as described in [Start Elasticsearch and Kibana in Docker](https://www.elastic.co/guide/en/elastic-stack-get-started/8.0/get-started-stack-docker.html#run-docker-secure), created connection to `https://localhost:9200`, specified username and password and it works.

**Comment by ppap6664180** [comment]
sorry, it's my problem
