### ISSUE TITLE
Not seeing search results

### ISSUE THREAD

**Issue by skoestler** [AntonShuvaev/elasticsearch4idea#68]
It is my understanding that the default query performed when double-clicking an index should match all documents but I am not seeing anything. I am able to retrieve a single document from the index using the plugin and querying the index via my app returns the expected results.

I suspect there may be a missing/incorrect setting on my index?

![Screen Shot 2022-02-22 at 8 45 49 AM](https://user-images.githubusercontent.com/493921/155157609-e398829c-481e-42d3-bf98-62725e2b52d7.png)

![Screen Shot 2022-02-22 at 8 45 46 AM](https://user-images.githubusercontent.com/493921/155157655-663dd6d4-1cac-4ee1-b794-136ea9ef48a3.png)

Thanks in advance for any help

(Edited to add version details)
Intellij 2021.2.3
Elasticsearch Plugin 2022.1.2-212
Elasticsearch 8.0.0

**Comment by AntonShuvaev** [comment]
Hello, thanks for reporting an issue. This bug is due to missing `_type` field in ES 8 response. Will be fixed ASAP.

**Comment by AntonShuvaev** [comment]
Fixed in 2022.1.4

**Comment by skoestler** [comment]
Got the update and works great. I really appreciate your quick response.

Thank you!
