### ISSUE TITLE
Kibana connector

### ISSUE THREAD

**Issue by cakarlen** [AntonShuvaev/elasticsearch4idea#69]
Quick question:

Is the Kibana connection object supposed to be able to authenticate to Kibana in order to run only Kibana REST APIs instead of Elasticsearch? Right now, it seems as if the Kibana connector will talk to Elasticsearch instead of talking to Kibana.

**Comment by AntonShuvaev** [comment]
Sometimes only Kibana exposed to the internet but not Elasticsearch. In this case it is possible to connect to Kibana and use it as proxy to Elasticsearch through `/api/console/proxy` API. The behavior is the same as connecting to Elasticsearch.

**Comment by cakarlen** [comment]
Ah I see now. Thanks for that clarification.

Is it then possible to call upon Kibana specific API endpoints as an enhancement to the plugin?

**Comment by AntonShuvaev** [comment]
This doesn't seem difficult since the Kibana API is prefixed with "api", unlike the Elasticsearch API. I will support this in a future update.

**Comment by AntonShuvaev** [comment]
Kibana REST API with autocompletion added in 2022.1.6.
