### ISSUE TITLE
Possibility to modify data in search results

### ISSUE THREAD

**Issue by evgenyvolferts** [AntonShuvaev/elasticsearch4idea#7]
It would be really great if you could implement data editing in search result either in a cell of results table or in popup window (like it's made in Kaizen, for example)

![image](https://user-images.githubusercontent.com/26716666/89901232-7b43e280-dbed-11ea-9a34-1c8a768fb949.png)

**Comment by AntonShuvaev** [comment]
Thanks for your suggestion! I will definitely consider it in future releases.

**Comment by sokool** [comment]
sorting by column would be also super feature
![image](https://user-images.githubusercontent.com/4784286/93392021-61429300-f870-11ea-99c9-91fa9bc3df8c.png)

If you add those two then I will stop using Kaizen :)

**Comment by AntonShuvaev** [comment]
Done.
