### ISSUE TITLE
The plugin uninstalls automatically

### ISSUE THREAD

**Issue by akmalick** [AntonShuvaev/elasticsearch4idea#70]
I have been noticing some weird behavior since yesterday. Generally upon successful installation the elasticsearch toolbar is visible, docked at the side of window. But sometimes the toolbar goes away when a new window is opened.
Also, I keep getting yellow cloud icon(sync icon at bottom right corner). I have to install the plugin again from marketplace.

I also got a plugin update notification and when updated and restarted IDE, I could see the same yellow icon sync warning and the plugin was not there in the installed plugins list.

![image](https://user-images.githubusercontent.com/5765159/155622545-507f7ff8-2f48-4bb0-93cc-aa3ed45bb760.png)

Upon lcicking on icon and selecting "Choose plugins to update" I get below pop:
![image](https://user-images.githubusercontent.com/5765159/155622625-1da329ed-9624-4dbe-8735-6b9961b6e6b5.png)

I then apply the changes and then it asks me to restart ide.  Once the ide restarts the plugin is available as usual.

Not sure why the plugin goes missing from time to time.

**Comment by AntonShuvaev** [comment]
Thanks for reporting an issue. Will be fixed ASAP.

**Comment by AntonShuvaev** [comment]
Fixed
