### ISSUE TITLE
Add checkbox to allow self-signed certificates

### ISSUE THREAD

**Issue by cakarlen** [AntonShuvaev/elasticsearch4idea#71]
In the latest update of the plugin, it seems like I am unable to connect to Elastic clusters that use self-signed certificates:

![image](https://user-images.githubusercontent.com/33635487/156802945-ebe2ebdd-7c43-4dfe-9a22-655ec08e3865.png)

Could you add the ability to connect to clusters using an insecure method?

**Comment by AntonShuvaev** [comment]
Hi @cakarlen, 

This error is because of certificate hostname verification which I have added in the previous update. I will add checkbox to force trusting certificate.

**Comment by AntonShuvaev** [comment]
Added in 2022.1.6
