### ISSUE TITLE
Where are favorites now?

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#72]
Hi,

From what I understood, [a change was made on IntelliJ](https://blog.jetbrains.com/idea/2021/10/intellij-idea-2021-3-eap-2/#new_bookmarks_tool_window) to remove the favorite window and replace it with a bookmarks window to simplify things.
I cannot find my favorites ES request in this new window, it worked fine with the previous favorites view but not with this one.
When I save a favorite, everything seems ok (no errors), but I cannot find it back later.

I might just be missing the favorites location, or it might be a bug I don't know.

Version: PhpStorm 2021.3.1

Thanks!

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting the issue, I didn't notice that Favorites tool window was removed in IntelliJ Platform 2021.3. I have moved favorite requests to Scratches and Consoles folder in 2022.1.6.
