### ISSUE TITLE
Cant fetch indicies anymore since latest update

### ISSUE THREAD

**Issue by leberknecht** [AntonShuvaev/elasticsearch4idea#73]
Since the latest update i cannot fetch indices anymore. Maybe it is related to my self-signed certs, not sure though.

https://user-images.githubusercontent.com/1165177/157440420-7f42215f-43c0-48c4-8030-f0e577d2e6c7.mp4

(what is not visible is that i accept the self-signed certs when the popup shows up)

**Comment by AntonShuvaev** [comment]
Hi, 

This is related to #71 . I have added checkbox to trust insecure certificate in 2022.1.6.

**Comment by leberknecht** [comment]
Cant you give me a hint where to find that checkbox? 
![image](https://user-images.githubusercontent.com/1165177/157626263-40678cd8-03f1-4557-9e85-3bdafadeaad3.png)

The problem seems more related to buggy migration of existing connections. I had a connection for `http://localhost:9200` where i had the same effect without SSL. After re-adding the problem disappeared.

**Comment by leberknecht** [comment]
Ah my plugin was outdated. Indeed, works now
