### ISSUE TITLE
How to re-register

### ISSUE THREAD

**Issue by danizen** [AntonShuvaev/elasticsearch4idea#74]
Anton,

I just bought a license for myself, and got my manager to approve the license for my sole web developer on this project. Although the plugin is working, and will discover indices and so on, it still shows "License expired".  This may be a logic hole - I bought the license after the trial license had expired.  However, I for certain see it in my JetBrains account.  I simply do not have the activation links you mention in the documentation - https://www.intellij-elasticsearch.com/docs/getting-started/activation/#activate-license.

What I see is as below:

<img width="986" alt="plugin-activation-issue" src="https://user-images.githubusercontent.com/4966193/159344342-432a2d39-21db-4553-8afb-91d1c6021598.png">

**Comment by AntonShuvaev** [comment]
Hello,

Could you try to restart your IDE and go to `Help | Register Plugins`. If plugin looks like expired click `Remove License` button and then activate license again with your account or activation code.

**Comment by danizen** [comment]
Thanks, that did it.   I also had to "Refresh license list".  First paid plugin problem.  Thanks for your help.]

BTW - this is all started because the index data looked stale.  With the help of your app, I figured out that Django's "m2m_changed" database signal is called both before a foreign key relationship is saved and afterwards.  The only safe way to send the modifications to Elasticsearch is *after* the web request is all done, but I had really wanted to explore updating Elasticsearch when changes are made.
