### ISSUE TITLE
Feature-Request: remember contents of editor/scratch

### ISSUE THREAD

**Issue by leberknecht** [AntonShuvaev/elasticsearch4idea#75]
Would it be possible to remember the contents of the editor window? At the moment the contents is lost if we close the tab and later on open it again. It would be cool if the plugin would remember what i had (per index/alias+connection-name? i guess..which is the same as tab-title).

**Comment by AntonShuvaev** [comment]
Hi,

You can use query consoles that are grouped per connection and saved in project tree `Scratches and Consoles | Elasticsearch Consoles` or create Scratch file with type `Elasticsearch` or create file with extension `es` in your project. See [documentation](https://www.intellij-elasticsearch.com/docs/features/console#open-console). Also you can use [Favorite requests](https://www.intellij-elasticsearch.com/docs/other-features/favorite-requests/). The documentation is a little obsolete, now favourite requests are saved in project tree `Scratches and Consoles | Elasticsearch Favorites`

**Comment by leberknecht** [comment]
Uh, didnt know that! Solves my problem, thanks :)
