### ISSUE TITLE
Cannot init component state

### ISSUE THREAD

**Issue by zoeliterally** [AntonShuvaev/elasticsearch4idea#76]
Everytime i start Intellij all Elasticsearch conections are gone and this [stacktrace](https://gist.github.com/saschanke/af9d16fe79887f17434f4ab22f59a92c) comes up.

I have already tried to reinstall the Plugin but the error persists.

Steps to reproduce:

Create a new Connection
![2022-04-22 08_00_49-Window](https://user-images.githubusercontent.com/1536360/164613220-996bb616-3982-44a9-a910-5b526a1cd4a8.png)
![2022-04-22 08_01_37-Window](https://user-images.githubusercontent.com/1536360/164613229-942d460e-9c0e-4694-8e5a-25aeee8fe86d.png)
![2022-04-22 08_02_17-Window](https://user-images.githubusercontent.com/1536360/164613233-1f105677-504f-4b1d-b8ad-82a17cb5068c.png)

Until restart, everything works just fine but after closing and reopening Intellij its gone.

![2022-04-22 08_07_34-Window](https://user-images.githubusercontent.com/1536360/164613751-0660fc81-e08d-4fd2-854d-0642525d59ea.png)

**Comment by AntonShuvaev** [comment]
Hi,

Can you try to remove `globalElasticsearchSettings.xml` file? It should be somewhere about `/Users/anton/Library/Application Support/JetBrains/IdeaIC2022.1/options/globalElasticsearchSettings.xml`.

**Comment by zoeliterally** [comment]
Hi,

now it keeps the connection, but forgets the authorization type and credentials after restart.

![2022-04-22 09_19_05-Window](https://user-images.githubusercontent.com/1536360/164626225-4db94067-71f3-460a-8297-fd0e47ef81cb.png)

**Comment by AntonShuvaev** [comment]
Try to specify authorization options again, then close and open IDE.

**Comment by zoeliterally** [comment]
Done and now it's working, thank you!
