### ISSUE TITLE
Filter indexes etc. by expression

### ISSUE THREAD

**Issue by danizen** [AntonShuvaev/elasticsearch4idea#77]
When I use the /_cat/indices API by hand, I can filter by an expression, and see only the indices that pertain to me.  However, the product doesn't allow me to do this.

The way my DevTools team runs Elasticsearch doesn't work very well - they don't use Shield (what used to be shield), and protect Elasticsearch by associating verbs with Basic Authentication through the proxy server (Apache httpd).  So, I should only be messing with  indices, aliases, and templates that match my prefix.

I do like the read-only feature - and I am using that in production.

**Comment by AntonShuvaev** [comment]
Hi, 

Good idea, I'll probably implement it next week.

**Comment by AntonShuvaev** [comment]
Added in 2022.1.7
