### ISSUE TITLE
suppor setPathPrefix() and apikey authorization

### ISSUE THREAD

**Issue by caster-Q** [AntonShuvaev/elasticsearch4idea#81]
support to access ES as the following methods
`curl "http://xxx.xxx.cn/cluserName/_cat/health"   -H  "Authorization: ApiKey XXXXXXXX="`

**Comment by AntonShuvaev** [comment]
Hi,

You can specify URL with prefix as http://xxx.xxx.cn/cluserName. This should work.
Regarding the API Key, this is a good suggestion, I will support it in the next release.

**Comment by caster-Q** [comment]
thanks

**Comment by AntonShuvaev** [comment]
Done
