### ISSUE TITLE
Command history improvements

### ISSUE THREAD

**Issue by matrimcauthondf** [AntonShuvaev/elasticsearch4idea#84]
This plugin is amazing! Makes my life so much easier. The command history particularly. It would be nice if it could do the following though:

1. Have a keyword search so I can find what I am looking for without reading through everything
2. Paste shouldn't close the window. I usually reuse several commands in a row.

I know favorites covers some of this but the search would be very nice in history too. Thanks!

**Comment by AntonShuvaev** [comment]
Hi, Thanks for the feedback.

These are great suggestions. I will definitely support this.

**Comment by AntonShuvaev** [comment]
Done.
