### ISSUE TITLE
not collect update

### ISSUE THREAD

**Issue by mazers0129** [AntonShuvaev/elasticsearch4idea#86]
when update nested value with table
it not update correctly

eg.
{"x": "kkk", "y":{"z": "123"}}
update "y.z" with table
it updated like this
{"x": "kkk", "y.z": "modify"}

**Comment by AntonShuvaev** [comment]
Thanks for reporting, I will investigate it.

**Comment by AntonShuvaev** [comment]
Fixed. Now nested values are edited as the whole nested object.
