### ISSUE TITLE
Allow configuring plugin keymaps

### ISSUE THREAD

**Issue by juhamust** [AntonShuvaev/elasticsearch4idea#88]
Unless I'm mistaken, the plugin does not currently allow modifying the keyboard shortcuts. For example, the `CMD + P` conflicts with the VS Code counterpart, and therefore I'd like to change the default.

![image](https://user-images.githubusercontent.com/781002/195154661-c54c42ab-0776-45aa-a99a-85aa048f6db8.png)

**Comment by AntonShuvaev** [comment]
Currently configuring keymap is not supported. I will add it in the next release.

**Comment by AntonShuvaev** [comment]
Done.

**Comment by juhamust** [comment]
Thanks! Working nicely 👍
