### ISSUE TITLE
[feature/discussion] allow insecure SSL?

### ISSUE THREAD

**Issue by leberknecht** [AntonShuvaev/elasticsearch4idea#9]
Other tools allow usage of self-signed certificates if explicitly wanted (like `--insecure` switch on cURL, or 'self-signed' option on Kaizen..which i think is doing the same. Not sure though, but what else can it be :))

I struggled a bit to get a working client-certificate for my self-signed elastic-cluster, so i would like to ask if it would be an option to add something like "allow insecure connections"?

**Comment by AntonShuvaev** [comment]
@leberknecht Good point. I have added option for self-signed certificate. Please let me know if it solves your issue.

**Comment by leberknecht** [comment]
Hm, it seems to behave a bit strange:
if i have the `Truststore` path blank but the self-signed checked, i get this:
![image](https://user-images.githubusercontent.com/1165177/90490987-9bb8f300-e13f-11ea-95fc-879d917de6b9.png)

But if i point it to a p12 file, it works. And if im not totally confused, it doesnt seem to matter if the selected p12 is valid for the endpoint or not oO

But overall: yes, it does solve my problem :) Feel free to close!
