### ISSUE TITLE
SSH Config

### ISSUE THREAD

**Issue by an2riy** [AntonShuvaev/elasticsearch4idea#90]
Is it possible to add the ability to read the file in Linux **~/.ssh/config** when connecting via SSH tunnel and use in the Host section the name which is described in the **~/.ssh/config**?
![image](https://user-images.githubusercontent.com/8819844/198021036-91266017-1547-467b-ba2f-58176f23e8a2.png)
Because Elasticsearch is located behind two servers and I have a config in the **~/.ssh/config** which go through these servers via ProxyJump.

**Comment by AntonShuvaev** [comment]
I will support ProxyJump and reading host from config in the next release.

**Comment by AntonShuvaev** [comment]
Released in 2022.3.0. You can now use the host alias from ~/.ssh/config when using the "OpenSSH Authentication Configuration and Agent" and the ProxyJump directive is also respected.

**Comment by an2riy** [comment]
Hello.
It is working.
Thanks for the implementation.

**Comment by an2riy** [comment]
> Released in 2022.3.0. You can now use the host alias from ~/.ssh/config when using the "OpenSSH Authentication Configuration and Agent" and the ProxyJump directive is also respected.

Hello.
It is working.
Thanks for the implementation.
