### ISSUE TITLE
Connection colors are very dim with dark theme

### ISSUE THREAD

**Issue by juhamust** [AntonShuvaev/elasticsearch4idea#91]
Minor colour issues (which is partially JetBrains issue, it seems):

## Connection colors

Provided colours are very dim & hard to separate from each other 🤔 

![image](https://user-images.githubusercontent.com/781002/200611682-a9e10012-6995-4281-8396-4ba67717f361.png)

For a reference, the similar issue can be seen in Database settings - but it also supports custom colors which allows to have any colour.

![image](https://user-images.githubusercontent.com/781002/200612031-01f9861a-d738-4b77-a8b0-fac8d7f57d47.png)

## Icon color

Unlike with other JetBrains panels, Elasticsearch -extension has coloured icon. See first screenshot.

**Comment by AntonShuvaev** [comment]
Good suggestion. I will do it.

**Comment by AntonShuvaev** [comment]
Done.

**Comment by juhamust** [comment]
Thanks! Works well.
