### ISSUE TITLE
Add "routing" field to the Bulk API export

### ISSUE THREAD

**Issue by SosthenG** [AntonShuvaev/elasticsearch4idea#92]
Hi,

For documents with relation (parent/child), the "routing" field is needed when indexing the children documents.
The Bulk API export does not allow to export this field.

Could it be added as a checkbox like the already optional "With ID" ?

Thanks!

**Comment by AntonShuvaev** [comment]
Hi,
Thanks for reporting the issue. I will do it in the next release.

**Comment by AntonShuvaev** [comment]
Released in 2022.3.2
