### ISSUE TITLE
Moving tabs resets query loosing changes

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/elasticsearch4idea#97]
When I open a tab by double clicking an index, by default I get a `match_all` query. If I make any modification to it (adding `sort`, changing `query`, etc.), and then rearrange the tabs by drag&drop, when I go again to this tab, the modified query is lost and I get the default `match_all` again.

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will fix it in the next update.

**Comment by AntonShuvaev** [comment]
Fixed. Please update to the version  2023.1.0
